#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=0:10:00
#PBS -l vmem=8gb
#PBS -N shapesig
#PBS -V

#for carbonate
module unload python
module load tensorflow

#time singularity exec -e docker://brainlife/tensorflow:N ./main.py
./main.py
