#!/bin/bash
#PBS -l nodes=1:ppn=16,walltime=0:10:00
#PBS -l vmem=15gb
#PBS -N shapesig
#PBS -V

SINGULARITYENV_PYTHONNOUSERSITE=true singularity exec -e docker://brainlife/tensorflow:1.12.0 ./main.py
